export const projects = [
  {
    id: 'beFit',
    title: 'BeFit v2',
    ongoing: false,
    app: 'Mobile & Web Application',
    description: "BeFit v2 is your ultimate fitness companion, offering a seamless way to monitor your weight-loss progress, diet, and workouts. Whether you're new to fitness or a seasoned enthusiast, BeFit v2 empowers you to achieve your wellness goals with ease and precision.",
    role: 'APP & WEB DEVELOPER',
    duration: 'Feb 2024 - Aug 2024',
    technologies: ['Next.js', 'Shadcn UI', 'Tailwind CSS', 'Supabase', 'PostgreSQL', 'Stripe', 'Swift'],
    codeLink: 'https://github.com/nhvn/befitv2app',
    liveLink: 'https://befit-v2.zachuri.com/login',
    prob: 'Tracking fitness progress can be cumbersome and fragmented across different platforms and methods. Users often struggle with managing their workouts, dietary intake, and weight measurements in one place, leading to inconsistencies and difficulties in maintaining a holistic view of their health and fitness journey.',
    sol: 'BeFit v2 consolidates fitness tracking into a single, user-friendly platform. By allowing users to log workouts, monitor calorie intake, and track weight measurements all in one app, BeFit v2 provides a seamless and comprehensive approach to fitness management. This integration ensures users can easily stay on top of their fitness goals, receive insights into their progress, and make informed decisions to enhance their wellness journey.',
    contribution: 'Enabled users to input dates for varied weight measurements, enhancing tracking versatility \n Fixed various bugs including the inability to delete weights \n Transformed the web app into an iOS mobile application, using Swift',
    team: 'Two other software engineers',
    image: '/img/beFit.png',
    sect1: 'Sketches',
    sect1content: 'For the website, I analyzed the layout and adapted it for a seamless mobile experience, focusing on consistency and ease of navigation across platforms. This is crucial for our fitness app, where user engagement and accessibility are key.',
    // sect1sub1: 'Drawings',
    // sect1sub1content: 'Subsection 1 content',
    // sect1sub1img1: '/img/beFit-Sketch.png',
    sect1img1: '/img/beFit-Sketch.png',
    sect2: 'Methodology',
    sect2content: 'I created a detailed architecture diagram to illustrate the interactions between UI, ViewModels, Data Management, and Networking. This diagram highlights key interactions, ensuring a cohesive and efficient user experience on both web and mobile.',
    sect2img1: '/img/beFitArch.png',
    sect3: 'Results',
    sect3content: 'This represents the envisioned design direction for my app. Currently, I am actively developing it using Swift and Xcode to ensure an exceptional user experience. While these designs may evolve, they serve as the foundation for further prototyping.',
    sect3img1: '/img/beFit-darkmode.png',
    sect3img2: '/img/beFit-dashboard.png',
    sect3img3: '/img/beFit-workouts.png',
    sect3img4: '/img/beFit-dietweight.png',
    sect4: 'Final Thoughts',
    sect4content: "Working on the BeFit v2 project was an enriching experience that allowed me to leverage my skills in mobile and web application development to create a comprehensive fitness companion app. Through a user-centric design approach, I focused on developing an intuitive and cohesive interface that seamlessly integrates essential features such as workout logging, dietary tracking, weight monitoring, and social interaction.\n\nThe iterative design process was crucial in ensuring the app met the real needs of fitness enthusiasts, providing them with a reliable tool to track their progress and stay motivated. Collaboration with my team members was invaluable, as we combined our expertise to tackle challenges and enhance the app's functionality and user experience.\n\nThis project reinforced the importance of meticulous attention to detail, agile development methodologies, and continuous user feedback in creating software solutions that are both practical and engaging. Overall, BeFit v2 aims to empower users on their fitness journeys, making it easier and more enjoyable to achieve their wellness goals.",
  },
  {
    id: 'taskmaster',
    title: 'Task Master',
    ongoing: false,
    app: 'Web Application',
    description: 'To-Do List App app allows users to create, edit, and delete tasks with due dates and priorities, as well as mark tasks as complete or incomplete. Users can register, log in, and log out, and their tasks are stored securely in a PostgreSQL database.',
    role: 'FULL-STACK DEVELOPER',
    duration: 'Apr 2023 - Jun 2023',
    technologies: ['React', 'Node.js', 'Express', 'PostgreSQL', 'MongoDB', 'HTML', 'CSS'],
    codeLink: 'https://github.com/nhvn/to-do-list',
    prob: '',
    sol: '',
    contribution: 'Built a secure PostgreSQL database from scratch and developed a robust API using Node.js and Express \n Created an intuitive user interface using React, integrating it with the back-end for seamless functionality',
    team: 'Two other software engineers',
    image: '/img/todo.png',
    sect1: 'Sketches',
    sect1content: 'In the initial design phase, I focused on creating intuitive and user-friendly interfaces. I sketched various layouts, considering factors like usability and aesthetic appeal. The goal was to create a design that would provide a seamless user experience while maintaining a clean and modern look.',
    sect1img1: '/img/todoSketch.png',
    sect2: 'Methodology',
    sect2content: "My approach was iterative and user-centric. I started with low-fidelity wireframes, gradually refining them based on user feedback and usability testing. I also considered the latest design trends and best practices, ensuring the design was both contemporary and intuitive. To enhance user productivity and organization, I incorporated dedicated sections for Today's Task, Agenda, and Objectives. The Today's Task section allows users to quickly view and prioritize their tasks for the day, while the Agenda section provides an overview of upcoming deadlines and events. The Objectives section allows users to set and track long-term goals, breaking them down into manageable tasks. Additionally, I included a versatile Bulletin Board feature, which functions as a digital cork board. Users can create and customize virtual sticky notes, enabling them to jot down reminders, ideas, or any other information they need to keep track of. The Bulletin Board seamlessly integrates with the to-do list, allowing users to effortlessly transform their notes into actionable tasks. This feature aims to provide a comprehensive workspace, fostering organization and productivity while catering to individual preferences and working styles.",
    sect3: 'Results',
    sect3content: 'The final design effectively balanced functionality and aesthetics. It provided users with a clear and easy-to-navigate interface, improving task management efficiency. The design was well-received by users, demonstrating the effectiveness of the user-centric design approach.',
    sect3img1: '/img/todoResult.png',
    sect3img2: '/img/todoResult2.png',
    sect4: 'Final Thoughts',
    sect4content: "Working on the Task Master project was a rewarding experience that allowed me to apply my full-stack development skills to create a practical and user-friendly application. Through an iterative and user-centric design process, I was able to develop an intuitive interface that seamlessly combines essential features like to-do lists, agendas, objectives, and a versatile bulletin board. The integration of these functionalities aimed to provide users with a comprehensive workspace that fosters productivity, organization, and customization. Throughout the project, I valued collaboration with my team members, leveraging our collective expertise to overcome challenges and deliver a polished final product. Overall, this project reinforced the importance of user-centered design, agile development methodologies, and attention to detail in creating effective software solutions that meet real-world needs.",
  },
  {
    id: 'oldPortfolio',
    title: 'Old Portfolio',
    ongoing: false,
    app: 'Web Application',
    description: 'A comprehensive showcase of my skills, experiences, and projects. This simple website was designed to be responsive and user-friendly, providing visitors with easy access to my work and contact information.',
    role: 'WEB DEVELOPER',
    duration: 'Apr 2023 - Jun 2023',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    codeLink: 'https://github.com/nhvn/nhvn.github.io',
    liveLink: 'https://nhvn.github.io/',
    contribution: 'Designed and developed the entire website from scratch \n Implemented responsive design principles to ensure a seamless experience across different devices \n Integrated a contact form for easy communication',
    image: '/img/portfolio.png',
    sect1: 'Sketches',
    sect1content: 'The project sketches visually represent the structure of the website, including the layout of the introduction, about, project, and contact sections. They also highlight the design elements of the navigation and footer. In addition, they depict how responsive design has been implemented to ensure a seamless user experience across different devices. Each sketch offers a clear depiction of the main components and their interplay, which enhances the understanding of the website’s design and functionality.',
    sect1img1: '/img/portfolioSketch.png',
    sect2: 'Methodology',
    sect2content: 'The project started with a design phase where the layout of the website was planned. The development phase involved coding the website using HTML, CSS, JavaScript, and Bootstrap. A contact form was integrated for easy communication. Responsive design principles were implemented to ensure the website looks good on all devices.',
    sect3: 'Results',
    sect3content: 'The portfolio website project yielded positive results. The website effectively showcases my skills, experiences, and projects, providing visitors with a comprehensive view of my capabilities. The responsive design ensures a seamless experience across different devices.',
    sect3img1: '/img/portfolioResult.png',
    sect3img2: '/img/portfolioResult2.png',
    sect4: 'Final Thoughts',
    sect4content: 'This is my first personal portfolio that I have ever made, after completing my program. It not only allowed me to showcase my skills and experiences but also gave me a platform to share my work with others. The project was a great opportunity to apply my full stack development skills in a real-world scenario.',
  },
  {
    id: 'smartLights',
    title: 'Smart Lighting Control System',
    ongoing: false,
    app: 'Physical + Digital Integration Product',
    description: "An automation solution for precise control of lights. This system enables control of up to 50 lights across 10 rooms with customizable schedules.",
    role: 'IoT Developer',
    duration: 'Feb 2023 - Mar 2023',
    technologies: ['Python', 'Flask', 'Raspberry Pi'],
    prob: '',
    sol: '',
    contribution: 'Engineered lighting automation solution using Python \n Utilized Raspberry Pi to interact with physical GPIO pins \n Used multithreading and Flask web framework to enable parallel control of lights \n Created web UI with Jinja templates for user management and scheduling',
    team: 'Two other software engineers',
    image: '/img/light.png',
    sect1: 'Sketches',
    sect1content: 'The initial phase of the Smart Lighting Control System project involved detailed sketches and wireframes to visualize the design and layout of the system. These sketches helped in planning the user interface and the flow of the control system, ensuring a user-friendly and efficient design.',
    sect1img1: '/img/lightSketch.png',
    sect2: 'Methodology',
    sect2content: 'The development process involved iterative prototyping and testing. I used Python for the core functionality and Flask for the web framework. Multithreading was implemented to allow parallel control of the lights, and Jinja templates were used to create the web UI. The system was tested thoroughly to ensure reliable performance.',
    sect3: 'Results',
    sect3content: 'The Smart Lighting Control System was successfully developed and implemented. It provided precise control of lights, allowing users to customize schedules and manage up to 50 lights across 10 rooms. The system was reliable and user-friendly, meeting the project’s goals.',
    sect3img1: '/img/lightResult.png',
    sect3img2: '/img/lightResult2.png',
    sect4: 'Final Thoughts',
    sect4content: "Working on the Smart Lighting Control System project was a valuable experience that allowed me to apply my IoT development skills in a practical context. I learned a lot about integrating hardware and software to create a seamless and efficient solution. The project's success demonstrated the importance of iterative prototyping, thorough testing, and user-centric design.",
  },
  {
    id: 'pumpkin',
    title: 'Pumpkin Lostte Game',
    ongoing: false,
    app: 'Web Application',
    role: 'GAME DEVELOPER',
    description: 'This game is a twist on Flappy Bird, where players guide Jerry to rescue his lost pumpkin by skillfully dodging obstacles. It is a nostalgic journey with a meaningful objective, born from a love for classic games. Currently playable on Windows.',
    technologies: ['JavaScript', 'HTML', 'CSS', 'Firebase'],
    codeLink: 'https://github.com/nhvn/first-browser-game',
    liveLink: 'https://pumpkin-lost-te.web.app/',
    image: '/img/pumpkin.png',
    contribution: 'Designed captivating game elements from scratch, ensuring a visually appealing and engaging user experience \n Developed the game using a combination of HTML, CSS, and JavaScript, implementing intricate game mechanics and interactions \n Managed the deployment process through Firebase, ensuring seamless integration and optimal performance across platforms',
    duration: 'Oct 2022 - Feb 2023',
    outcome: 'I developed ‘Pumpkin Lostte’, where players navigate through barriers to rescue a lost pumpkin, adding an actual destination to reach, unlike the endless gameplay of ‘Flappy Bird’.',
    sect1: 'Sketches',
    sect1content: 'The game design process was centered around crafting an immersive gameplay experience. The focus was on the game mechanics, where the player would have to navigate through a series of hurdles. The player character was constantly pursued, adding a layer of thrill and urgency to the game. This chase element was integral to the gameplay, challenging the player’s skills and decision-making in real-time. The design sketches reflected these mechanics, illustrating the dynamic and interactive nature of the game.',
    sect1img1: '/img/pumpkinSketch.png',
    sect1img2: '/img/pumpkinSketch2.png',
    sect2: 'Methodology',
    sect2content: 'The development process was iterative, beginning with a basic game loop and progressively incorporating features such as barrier navigation and game over conditions. A significant focus was placed on the individual designs of the game elements. The character “Jerry”, the “Pumpkin”, the “Chaser”, and the “Black Barriers” were all meticulously designed to enhance the gameplay experience. The designs for the “Chaser” and “Black Barriers” were particularly detailed, crafted carefully on my notes app. User feedback was integrated at each stage, further refining the game and enriching the player’s experience.',
    sect3: 'Results',
    sect3content: 'The final game provides a challenging yet enjoyable gaming experience. The unique twist of having an actual destination adds a new dimension to the gameplay, making it stand out from similar games. The Halloween-themed design was well-received by players, adding to the game’s appeal.',
    sect3img1: '/img/pumpkinResult.png',
    sect3img2: '/img/pumpkinResult2.png',
    sect4: 'Final Thoughts',
    sect4content: 'This project is my first milestone project from my bootcamp program, and I am proud of what I have accomplished so far. This is a JavaScript browser game built with HTML and CSS. I created this project around Halloween, so I decided to make it Halloween-themed. I designed some elements of the game from scratch, like the black barriers that players should avoid touching, or they lose. The game has room for improvement, but considering my knowledge at the time, I think it is awesome. Please feel free to try it out if you dare. It is a challenging game, so do not hesitate to give it multiple attempts.',
  },
  ];

  // >>>> THIS IS A TEMPLATE <<<<
  // { 
  //   id: '',
  //   title: '',
  //   ongoing: true,
  //   app: '',
  //   description: "",
  //   role: '',
  //   duration: '',
  //   technologies: ['', ''],
  //   codeLink: '',
  //   liveLink: '',
  //   prob: '',
  //   sol: '',
  //   contribution: '',
  //   team: '',
  //   image: '',
  //   sect1: '', SECTIONS
  //   sect1content: '',
  //   sect1img1: '',
  //   sect1img2: '',
  //   sect1img3: '',
  //   sect1sub1: '', SUBSECTIONS
  //   sect1sub1content: '',
  //   sect1sub1img1: '',
  //   sect2: '',
  //   sect2content: '',
  //   sect2img1: '',
  //   sect2img2: '',
  //   sect2img3: '',
  //   sect3: '',
  //   sect3content: '',
  //   sect3img1: '',
  //   sect3img2: '',
  //   sect3img3: '', (... currently goes up to 6 sections)
  //   sect4: 'Final Thoughts',
  //   sect4content: "",
  // },